### PR TITLE
MAINT-41089: Make sure that the title of uploaded file with special characters is not encoded.

### PR DESCRIPTION
**Pull request by mdiha**
When uploading a file that it's title contains special characters it is changed by replacing the special characters by the character (-) due to JCR limitation, these changes are required for the created node name property but it is not required for the title so i made sure to apply these changes only for the file's node name by keeping its title as the original value.

### CODE REVIEW

**Review by ahamdi — APPROVED** [review]

**Review by ahamdi — CHANGES_REQUESTED** [review]
Description required

**Comment by mdiha** [comment]
> Description required

Description added

**Comment by ahamdi** [comment]
Did you test for cyrillic characters ?

**Comment by mdiha** [comment]
> Did you test for cyrillic characters ?

I did test it for cyrillic characters and it works fine

**Review by ahamdi — APPROVED** [review]

**Pull request merged**
