### PR TITLE
Task 48159 : Warning popup UI is badly displayed

### PR DESCRIPTION
**Pull request by Rdidmohamedelhadi**
**Problem:** we use two keys that are not added to the properties file.
 **the solution**: I added these keys `attachments.filesFoldersSelector.popup.button.ok`  `attachments.filesFoldersSelector.action.delete.popup.button.cancel` to file properties

### CODE REVIEW

**Review by rdenarie — COMMENTED** [review]
Code is ok, but waiting for a PO precision on task

**Comment by Rdidmohamedelhadi** [comment]
> Code is ok, but waiting for a PO precision on task

The **ok** (`attachments.filesFoldersSelector.popup.button.ok`) key is displayed in the warning popup when you already have the folder name. The **cancel** (`attachments.filesFoldersSelector.action.delete.popup.button.cancel`) key is displayed when you delete a folder, so in this case, you need two buttons (**ok**, **cancel**) !! cc @mzorai

**Review by rdenarie — COMMENTED** [review]
Can you update the commit message, to follow the format 
<Title>
<Empty line>
<Description> (answering WHY ? and HOW ?)

Thanks

**Review by rdenarie — APPROVED** [review]
Approved

Next time, can you try to use imperative form (This change modifies ...) instead of using I

Thanks

**Comment by Rdidmohamedelhadi** [comment]
> Next time, can you try to use imperative form (This change modifies ...) instead of using I

ok !

**Pull request merged**
