### PR TITLE
MAINT-45781: Fix the nodeType of a folder added from attachments drawer

### PR DESCRIPTION
**Pull request by hakermi**
**ISSUE** : when adding a folder via the attachments drawer the type of folder is **nt:unstructure** which is a super type node and not the same behavior when adding a folder via the explorer which the type is **nt:folder**  these contradictions make it impossible to rearrange folders because it's impossible to put **nt:unstructure** folder inside an **nt:folder**.

**Fix** the nodeType of a folder added from attachments drawer by updating the rest endpoint to have the possibility of specifying the node type in the rest call to other future use and need or a default value will be assigned nt:folder.

### CODE REVIEW

**Review by rdenarie — CHANGES_REQUESTED** [review]
Can you redo the PR in order to have only your commit into ?
It is not possible to review currently

**Comment by hakermi** [comment]
> Can you redo the PR in order to have only your commit into ?
> It is not possible to review currently

done

**Review by rdenarie — CHANGES_REQUESTED** [review]
Can you complete the commit message ? 
Your commit message should answer two questions : 
Why this change is needed ?
How your fix resolved the problem ?

The code is ok, and I'll validate the PR when the message is ok.

Thanks

**Comment by hakermi** [comment]
> Can you complete the commit message ?
> Your commit message should answer two questions :
> Why this change is needed ?
> How your fix resolved the problem ?
> 
> The code is ok, and I'll validate the PR when the message is ok.
> 
> Thanks

PR description updated

**Review by rdenarie — APPROVED** [review]
Approved. Dont forget to put your PR description as commit message when squashing.

**Pull request merged**
