### PR TITLE
Merge mip 134

### PR DESCRIPTION
**Pull request by rdenarie**

### CODE REVIEW

**Review by ahamdi — COMMENTED** [review]
We need to remove the commented blocks IMO?

**Comment by rdenarie** [comment]
@ahamdi done

**Review by azayati — APPROVED** [review]
LGTM

**Review by ahamdi — APPROVED** [review]

**Review by mkrout — APPROVED** [review]

**Comment by rdenarie** [comment]
Reorganize Commit, can you revalidate @ahamdi

**Review by ahamdi — APPROVED** [review]

**Pull request merged**
