### PR TITLE
ECMS-7444:Property definition is not found exception after deploying …

### PR DESCRIPTION
**Pull request by mkrout**
…the "Spaces-Categories" Add-on

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
LGTM
@boubaker can you have a look please (since it is related to the clean up of Social JCR nodes) ?

**Comment by mkrout** [comment]
New PR https://github.com/exodev/ecms/pull/202

**Comment by boubaker** [comment]
Just some questions to know if this is the best solution:
- Shouldn't we use collaboration WS instead of Social for ECMS categories ? (So the new addon will not face this problem anymore)
- Why do we need exo:dateModified property ? In the source code, I don't see why we should add a persistent information while the usage is for processing (to know if the node is new or not).

**Comment by mkrout** [comment]
- We are using the collaboration WS to store categories, but the issue is related to the target node of the category ("soc:spacedefinition") that is stored in social WS.
- I don't want to delete this property since I don't know if it is needed somewhere or not.

**Pull request closed without merging**
