### PR TITLE
MAINT-36446: Fix sections labels are not i18n in file attachment drawer

### PR DESCRIPTION
**Pull request by hakermi**
**ISSUE**: In the attachment drawer the section labels are not well translated because of missed keys and unhanded translation for their names
**FIX**: Add new keys for the section and get the i18n values when display these labels

### CODE REVIEW

**Review by rdenarie — DISMISSED** [review]

**Comment by rdenarie** [comment]
@hakermi please resolve conflict

**Comment by hakermi** [comment]
> @hakermi please resolve conflict

Done

**Review by rdenarie — COMMENTED** [review]
Should we add french values to test on acc ?

**Comment by hakermi** [comment]
> Should we add french values to test on acc ?

Ok, added

**Review by rdenarie — APPROVED** [review]

**Pull request merged**
